
const resources = {
    en: {
        translation: {
            "Language": "Language",
            "Theme": "Theme",
            "Light": "Light",
            "Dark": "Dark",
            "Symbol": "Symbol",
            "Ref": "Ref",
            "Ceil": "Ceil",
            "Floor": "Floor",
            "Bid side": "Bid",
            "Matched": "Matched",
            "Ask side": "Ask",
            "T.Vol": "T.Vol",
            "Prices": "Prices",
            "Remain": "Remain",
            "Foreign": "Foreign",
            "Prc 3": "Prc 3",
            "Vol 3": "Vol 3",
            "Prc 2": "Prc 2",
            "Vol 2": "Vol 2",
            "Prc 1": "Prc 1",
            "Vol 1": "Vol 1",
            "Price": "Price",
            "Vol": "Vol",
            "High": "High",
            "Avg": "Avg",
            "Low": "Low",
            "Bid": "Bid",
            "Ask": "Ask",
            "Bought": "Bought",
            "Sold": "Sold",
            "Log Out": "Log Out",
            "Price Board": "Price Board",
            "Quick Order": "Quick Order",
            "Stock Market": "Stock Market",
            "Derivative Market": "Derivative Market",
            "Volumn": "Volumn",
            "Odd lot market": "Odd lot market",
            "TransVol": "TransVol",
            "TransVal": "TransVal",
            "PutthroughTransVol": "Putthrough TransVol",
            "PutthroughTransVal": "Putthrough TransVal",
            "Text search Stock ID": "Search for Stock ID"
        }
    },
    vi: {
        translation: {
            "Language": "Ngôn ngữ",
            "Theme": "Giao diện",
            "Light": "Sáng",
            "Dark": "Tối",
            "Symbol": "Mã CK",
            "Ref": "TC",
            "Ceil": "Trần",
            "Floor": "Sàn",
            "Bid side": "Bên mua",
            "Matched": "Khớp lệnh",
            "Ask side": "Bên bán",
            "T.Vol": "Tổng KL",
            "Prices": "Giá",
            "Remain": "Dư",
            "Foreign": "ĐTNN",
            "Prc 3": "Giá 3",
            "Vol 3": "KL 3",
            "Prc 2": "Giá 2",
            "Vol 2": "KL 2",
            "Prc 1": "Giá 1",
            "Vol 1": "KL 1",
            "Price": "Giá",
            "Vol": "KL",
            "High": "Cao",
            "Avg": "TB",
            "Low": "Thấp",
            "Bid": "Mua",
            "Ask": "Bán",
            "Bought": "Mua",
            "Sold": "Bán",
            "Log Out": "Đăng Xuất",
            "Price Board": "Bảng giá",
            "Quick Order": "Đặt Lệnh",
            "Stock Market": "Đơn vị TT cơ sở",
            "Derivative Market": "Đơn vị TT phát sinh",
            "Volumn": "Khối lượng",
            "Odd lot market": "Đơn vị TT lô lẻ",
            "TransVol": "KLGD",
            "TransVal": "GTGD",
            "PutthroughTransVol": "KL thỏa thuận",
            "PutthroughTransVal": "GT thỏa thuận",
            "Text search Stock ID": "Tìm kiếm mã CK"
        }
    }
};

export default resources;